name: Hexo Deploy

on:
  push:
    branches:
      - blog-code

jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    
    # 检查工作流是否可以访问 actions   
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # 安装 NodeJs
    - name: Setup Node.js 12.x 
      uses: actions/setup-node@master
      with:
        node-version: "12.x"
    
    # 安装 Hexo 的依赖库
    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install
    
    # 设置 Hexo 部署的私钥
    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    # 设置 Git 信息
    - name: Setup Git Infomation
      run: | 
        git config --global user.name "zhjAdm" 
        git config --global user.email "zhjAdm@gmail.com"

    # 部署 Hexo 静态文件到博客所在的分支
    - name: Deploy Hexo 
      run: |
        hexo clean
        hexo generate 
        hexo deploy