name: Hexo Auto-Deploy
on:
  push:
    branches: 
      - hexo-blog-backup

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
      
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: 3. Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: 4. Install hexo dependencies 
      run: |
        npm install hexo-cli -g
        npm install
        
    - name: 5. hexo generate public files...
      run: |
        hexo clean
        hexo generate  

    - name: 6. hexo deploy ...
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/zhjAdm/zhjAdm.github.io.git
      # 将编译后的博客文件推送到指定仓库
      run: |
        cd ./public && git init && git add .
        git config user.name "zhjAdm"
        git config user.email "zhjAdm@gmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.GH_TOKEN }}@$GITHUB_REPO" master:hexo
